 services:
  next:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    ports:
      - "${HOST_PORT:-3000}:3000"
    volumes:
      - ./src:/app
    environment:
      - NODE_ENV=development